// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amantiq;

namespace company_service.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20201002203104_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("amantiq.model.Benefit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<string>("PackageId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SpendAccountRecordId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("benefits");
                });

            modelBuilder.Entity("amantiq.model.BenefitPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CarryForwardPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CarryForwardPeriodValue")
                        .HasColumnType("integer");

                    b.Property<int>("CarryForwardValue")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsCarryForward")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProRated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodValue")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("benefit_packages");
                });

            modelBuilder.Entity("amantiq.model.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<List<string>>("Admins")
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("AmantiqAdmins")
                        .HasColumnType("jsonb");

                    b.Property<string>("BranchOf")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("amantiq.model.CompanyHoliday", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<List<string>>("Holidays")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("company_holidays");
                });

            modelBuilder.Entity("amantiq.model.Holiday", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<List<string>>("Applicable")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("holdays");
                });

            modelBuilder.Entity("amantiq.model.Leave", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SpendAccountRecordId")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("leaves");
                });

            modelBuilder.Entity("amantiq.model.LeavePackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CarryForwardPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CarryForwardPeriodValue")
                        .HasColumnType("integer");

                    b.Property<int>("CarryForwardValue")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsCarryForward")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProRated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodValue")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("leave_packages");
                });

            modelBuilder.Entity("amantiq.model.SpendAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ExpiryBalance")
                        .HasColumnType("integer");

                    b.Property<string>("PackageId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpendBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("spend_account");
                });

            modelBuilder.Entity("amantiq.model.SpendAccountRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PackageId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SpendAccountId")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SpendBalance")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("spend_account_records");
                });
#pragma warning restore 612, 618
        }
    }
}
